"""
Fire-and-forget signal event logger.

Captures full context for every signal generated by the coordinator:
technical indicators, sentiment scores, debate outcomes, and trade execution
status.  Outcome columns (price_3d, price_5d, etc.) are populated later by
the outcome_tracker module.

The ``log()`` method **never raises** — if the DB write fails the trading
pipeline continues unaffected.

Usage::

    from analytics.signal_logger import SignalLogger

    logger = SignalLogger()            # uses the default DB
    logger.log(signal_data)            # fire-and-forget
    rows = logger.get_signals("AAPL")  # read back for analytics
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone

from storage.database import Database

log = logging.getLogger(__name__)

_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS signal_events (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp           TEXT    NOT NULL,
    session             TEXT,
    ticker              TEXT    NOT NULL,
    strategy            TEXT,
    signal              TEXT    NOT NULL,
    confidence          REAL,
    rsi                 REAL,
    sma_ratio           REAL,
    volume_ratio        REAL,
    sentiment_score     REAL,
    news_score          REAL,
    social_score        REAL,
    bull_case           TEXT,
    bear_case           TEXT,
    debate_outcome      TEXT,
    price_at_signal     REAL,
    trade_executed      INTEGER NOT NULL DEFAULT 0,
    trade_id            TEXT,
    price_3d            REAL,
    price_5d            REAL,
    price_10d           REAL,
    outcome_3d_pct      REAL,
    outcome_5d_pct      REAL,
    outcome_10d_pct     REAL,
    outcome_correct     INTEGER
)
"""


class SignalLogger:
    """Log every signal event for post-hoc analytics.

    All public methods are safe to call from the hot path — they catch
    and log exceptions internally so the trading pipeline is never
    disrupted.
    """

    def __init__(self, db: Database | None = None) -> None:
        self._db = db or Database()
        self._ensure_table()

    def _ensure_table(self) -> None:
        try:
            with self._db._connect() as conn:
                conn.executescript(_CREATE_TABLE)
        except Exception as exc:
            log.warning("signal_events table creation failed: %s", exc)

    def log(self, signal_data: dict) -> None:
        """Fire and forget. Never raises. Logs to signal_events table."""
        try:
            now = signal_data.get(
                "timestamp",
                datetime.now(timezone.utc).isoformat(),
            )
            with self._db._connect() as conn:
                conn.execute(
                    """
                    INSERT INTO signal_events
                        (timestamp, session, ticker, strategy, signal,
                         confidence, rsi, sma_ratio, volume_ratio,
                         sentiment_score, news_score, social_score,
                         bull_case, bear_case, debate_outcome,
                         price_at_signal, trade_executed, trade_id)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        now,
                        signal_data.get("session"),
                        signal_data.get("ticker", ""),
                        signal_data.get("strategy"),
                        signal_data.get("signal", ""),
                        signal_data.get("confidence"),
                        signal_data.get("rsi"),
                        signal_data.get("sma_ratio"),
                        signal_data.get("volume_ratio"),
                        signal_data.get("sentiment_score"),
                        signal_data.get("news_score"),
                        signal_data.get("social_score"),
                        signal_data.get("bull_case"),
                        signal_data.get("bear_case"),
                        signal_data.get("debate_outcome"),
                        signal_data.get("price_at_signal"),
                        int(signal_data.get("trade_executed", 0)),
                        signal_data.get("trade_id"),
                    ),
                )
        except Exception as exc:
            log.warning("SignalLogger.log() failed (non-fatal): %s", exc)

    def get_signals(
        self,
        ticker: str | None = None,
        days: int = 30,
    ) -> list[dict]:
        """Read signals for analytics. Optional ticker filter."""
        try:
            cutoff = (
                datetime.now(timezone.utc) - timedelta(days=days)
            ).isoformat()
            if ticker:
                sql = (
                    "SELECT * FROM signal_events "
                    "WHERE ticker = ? AND timestamp >= ? "
                    "ORDER BY id DESC"
                )
                params: tuple = (ticker.upper(), cutoff)
            else:
                sql = (
                    "SELECT * FROM signal_events "
                    "WHERE timestamp >= ? "
                    "ORDER BY id DESC"
                )
                params = (cutoff,)
            with self._db._connect() as conn:
                rows = conn.execute(sql, params).fetchall()
                return [dict(row) for row in rows]
        except Exception as exc:
            log.warning("SignalLogger.get_signals() failed: %s", exc)
            return []
