"""
Fire-and-forget signal event logger.

Captures full context for every signal generated by the coordinator:
technical indicators, sentiment scores, debate outcomes, and trade execution
status.  Outcome columns (price_3d, price_5d, etc.) are populated later by
the outcome_tracker module.

The ``log()`` method **never raises** — if the DB write fails the trading
pipeline continues unaffected.

Usage::

    from analytics.signal_logger import SignalLogger

    logger = SignalLogger()            # uses the default DB
    logger.log(signal_data)            # fire-and-forget
    rows = logger.get_signals("AAPL")  # read back for analytics
"""

from __future__ import annotations

import json
import logging
import sqlite3
from datetime import datetime, timedelta, timezone

from storage.database import Database

log = logging.getLogger(__name__)

_CREATE_FORWARD_TABLE = """
CREATE TABLE IF NOT EXISTS forward_signals (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at          TEXT    NOT NULL,
    source_session      TEXT    NOT NULL,
    target_session      TEXT    NOT NULL,
    ticker              TEXT    NOT NULL,
    signal              TEXT    NOT NULL,
    confidence          REAL,
    price_at_signal     REAL,
    strategy_name       TEXT,   -- DEPRECATED for attribution (B3, R spec
                                -- item 3): misattributes the vote supplier
                                -- in 19/24 era rows (it records the router
                                -- primary / caller label, NOT which strategy
                                -- voted).  Kept only for the portfolio-cap
                                -- strategy resolution in the cached US_OPEN
                                -- executor.  For attribution, read
                                -- vote_vector_json / strongest_supplier or
                                -- the signal_attribution table instead.
    stop_loss           REAL,
    take_profit         REAL,
    status              TEXT    NOT NULL DEFAULT 'pending',
    resolved_at         TEXT,
    invalidated_reason  TEXT
)
"""

# B3 (A1): vote-vector columns added to forward_signals via idempotent
# ALTER TABLE so the executing session can read the vector back instead
# of re-inferring it.  All confidences on the 0-1 scale.
_FORWARD_VOTE_COLUMNS: list[tuple[str, str]] = [
    ("vote_vector_json", "TEXT"),      # per-strategy signals/confs
    ("directional_count", "INTEGER"),
    ("strongest_supplier", "TEXT"),
    ("boost_applied", "REAL"),
    ("conf_pre_floor", "REAL"),
    ("conf_post_floor", "REAL"),
    ("evaluated_at", "TEXT"),
]

_CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS signal_events (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp           TEXT    NOT NULL,
    session             TEXT,
    ticker              TEXT    NOT NULL,
    strategy            TEXT,
    signal              TEXT    NOT NULL,
    confidence          REAL,
    rsi                 REAL,
    sma_ratio           REAL,
    volume_ratio        REAL,
    sentiment_score     REAL,
    news_score          REAL,
    social_score        REAL,
    bull_case           TEXT,
    bear_case           TEXT,
    debate_outcome      TEXT,
    price_at_signal     REAL,
    trade_executed      INTEGER NOT NULL DEFAULT 0,
    trade_id            TEXT,
    signal_path         TEXT,
    price_3d            REAL,
    price_5d            REAL,
    price_10d           REAL,
    outcome_3d_pct      REAL,
    outcome_5d_pct      REAL,
    outcome_10d_pct     REAL,
    outcome_correct     INTEGER
)
"""


class SignalLogger:
    """Log every signal event for post-hoc analytics.

    All public methods are safe to call from the hot path — they catch
    and log exceptions internally so the trading pipeline is never
    disrupted.
    """

    def __init__(self, db: Database | None = None) -> None:
        self._db = db or Database()
        self._ensure_table()

    def _ensure_table(self) -> None:
        try:
            with self._db._connect() as conn:
                conn.executescript(_CREATE_TABLE)
                conn.executescript(_CREATE_FORWARD_TABLE)
                # Add regime column if missing (migration for existing DBs)
                try:
                    conn.execute("ALTER TABLE signal_events ADD COLUMN regime TEXT")
                except Exception:
                    pass  # column already exists
                # Add macro_context_used column if missing (MacroContextAgent
                # measurement hook — future analytics can compare debate
                # outcomes with vs without macro context).
                try:
                    conn.execute(
                        "ALTER TABLE signal_events "
                        "ADD COLUMN macro_context_used INTEGER DEFAULT 0"
                    )
                except Exception:
                    pass  # column already exists
                # Phase 2d attribution — record which fusion path produced
                # the combined signal ("CLUSTER" or "FUSION_FALLBACK").
                try:
                    conn.execute(
                        "ALTER TABLE signal_events ADD COLUMN signal_path TEXT"
                    )
                except Exception:
                    pass  # column already exists
                # B3 (A1): forward_signals vote-vector columns.  Same
                # idempotent-ALTER pattern as earnings_source_eval
                # (time_of_day): swallow only "duplicate column".
                for col, typedef in _FORWARD_VOTE_COLUMNS:
                    try:
                        conn.execute(
                            f"ALTER TABLE forward_signals "
                            f"ADD COLUMN {col} {typedef}"
                        )
                    except sqlite3.OperationalError as exc:
                        if "duplicate column" not in str(exc).lower():
                            raise
        except Exception as exc:
            log.warning("signal_events table creation failed: %s", exc)

    def log(self, signal_data: dict) -> None:
        """Fire and forget. Never raises. Logs to signal_events table."""
        try:
            now = signal_data.get(
                "timestamp",
                datetime.now(timezone.utc).isoformat(),
            )
            with self._db._connect() as conn:
                conn.execute(
                    """
                    INSERT INTO signal_events
                        (timestamp, session, ticker, strategy, signal,
                         confidence, rsi, sma_ratio, volume_ratio,
                         sentiment_score, news_score, social_score,
                         bull_case, bear_case, debate_outcome,
                         price_at_signal, trade_executed, trade_id,
                         regime, macro_context_used, signal_path)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        now,
                        signal_data.get("session"),
                        signal_data.get("ticker", ""),
                        signal_data.get("strategy"),
                        signal_data.get("signal", ""),
                        signal_data.get("confidence"),
                        signal_data.get("rsi"),
                        signal_data.get("sma_ratio"),
                        signal_data.get("volume_ratio"),
                        signal_data.get("sentiment_score"),
                        signal_data.get("news_score"),
                        signal_data.get("social_score"),
                        signal_data.get("bull_case"),
                        signal_data.get("bear_case"),
                        signal_data.get("debate_outcome"),
                        signal_data.get("price_at_signal"),
                        int(signal_data.get("trade_executed", 0)),
                        signal_data.get("trade_id"),
                        signal_data.get("regime"),
                        int(bool(signal_data.get("macro_context_used", 0))),
                        signal_data.get("signal_path"),
                    ),
                )
        except Exception as exc:
            log.warning("SignalLogger.log() failed (non-fatal): %s", exc)

    def get_signals(
        self,
        ticker: str | None = None,
        days: int = 30,
    ) -> list[dict]:
        """Read signals for analytics. Optional ticker filter."""
        try:
            cutoff = (
                datetime.now(timezone.utc) - timedelta(days=days)
            ).isoformat()
            if ticker:
                sql = (
                    "SELECT * FROM signal_events "
                    "WHERE ticker = ? AND timestamp >= ? "
                    "ORDER BY id DESC"
                )
                params: tuple = (ticker.upper(), cutoff)
            else:
                sql = (
                    "SELECT * FROM signal_events "
                    "WHERE timestamp >= ? "
                    "ORDER BY id DESC"
                )
                params = (cutoff,)
            with self._db._connect() as conn:
                rows = conn.execute(sql, params).fetchall()
                return [dict(row) for row in rows]
        except Exception as exc:
            log.warning("SignalLogger.get_signals() failed: %s", exc)
            return []

    # ------------------------------------------------------------------
    # Forward signals (EOD → US_OPEN execution pipeline)
    # ------------------------------------------------------------------

    def store_forward_signal(self, data: dict) -> int | None:
        """Store an EOD signal for next-day execution. Never raises.

        B3 (A1): optional vote-vector fields (``vote_vector_json``,
        ``directional_count``, ``strongest_supplier``, ``boost_applied``,
        ``conf_pre_floor``, ``conf_post_floor``, ``evaluated_at``) are
        written in a SECOND statement so a vote-vector write failure can
        never lose the forward row itself.
        """
        try:
            now = datetime.now(timezone.utc).isoformat()
            with self._db._connect() as conn:
                cur = conn.execute(
                    """
                    INSERT INTO forward_signals
                        (created_at, source_session, target_session, ticker,
                         signal, confidence, price_at_signal, strategy_name,
                         stop_loss, take_profit, status)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending')
                    """,
                    (
                        now,
                        data.get("source_session", "EOD"),
                        data.get("target_session", "US_OPEN"),
                        data.get("ticker", ""),
                        data.get("signal", ""),
                        data.get("confidence"),
                        data.get("price_at_signal"),
                        data.get("strategy_name"),
                        data.get("stop_loss"),
                        data.get("take_profit"),
                    ),
                )
                row_id = cur.lastrowid
                try:
                    vector = data.get("vote_vector_json")
                    if vector is not None and not isinstance(vector, str):
                        vector = json.dumps(vector)
                    conn.execute(
                        """
                        UPDATE forward_signals
                        SET vote_vector_json = ?, directional_count = ?,
                            strongest_supplier = ?, boost_applied = ?,
                            conf_pre_floor = ?, conf_post_floor = ?,
                            evaluated_at = ?
                        WHERE id = ?
                        """,
                        (
                            vector,
                            data.get("directional_count"),
                            data.get("strongest_supplier"),
                            data.get("boost_applied"),
                            data.get("conf_pre_floor"),
                            data.get("conf_post_floor"),
                            data.get("evaluated_at"),
                            row_id,
                        ),
                    )
                except Exception as exc:
                    log.warning(
                        "store_forward_signal() vote-vector write failed "
                        "(forward row %s kept, non-fatal): %s",
                        row_id, exc,
                    )
                return row_id
        except Exception as exc:
            log.warning("store_forward_signal() failed (non-fatal): %s", exc)
            return None

    def get_pending_forward_signals(
        self,
        target_session: str = "US_OPEN",
        ticker: str | None = None,
    ) -> list[dict]:
        """Return pending forward signals for the given target session."""
        try:
            if ticker:
                sql = (
                    "SELECT * FROM forward_signals "
                    "WHERE status = 'pending' AND target_session = ? "
                    "AND ticker = ? ORDER BY id DESC"
                )
                params: tuple = (target_session, ticker.upper())
            else:
                sql = (
                    "SELECT * FROM forward_signals "
                    "WHERE status = 'pending' AND target_session = ? "
                    "ORDER BY id DESC"
                )
                params = (target_session,)
            with self._db._connect() as conn:
                rows = conn.execute(sql, params).fetchall()
                return [dict(row) for row in rows]
        except Exception as exc:
            log.warning("get_pending_forward_signals() failed: %s", exc)
            return []

    def update_forward_signal(
        self,
        signal_id: int,
        status: str,
        reason: str | None = None,
    ) -> None:
        """Update a forward signal's status. Never raises."""
        try:
            now = datetime.now(timezone.utc).isoformat()
            with self._db._connect() as conn:
                conn.execute(
                    """
                    UPDATE forward_signals
                    SET status = ?, resolved_at = ?, invalidated_reason = ?
                    WHERE id = ?
                    """,
                    (status, now, reason, signal_id),
                )
        except Exception as exc:
            log.warning("update_forward_signal() failed (non-fatal): %s", exc)

    def expire_stale_forward_signals(self, max_age_hours: int = 24) -> int:
        """Mark pending forward signals older than *max_age_hours* as expired."""
        try:
            cutoff = (
                datetime.now(timezone.utc) - timedelta(hours=max_age_hours)
            ).isoformat()
            with self._db._connect() as conn:
                cur = conn.execute(
                    """
                    UPDATE forward_signals
                    SET status = 'expired',
                        resolved_at = ?,
                        invalidated_reason = 'stale (> 24h)'
                    WHERE status = 'pending' AND created_at < ?
                    """,
                    (datetime.now(timezone.utc).isoformat(), cutoff),
                )
                return cur.rowcount
        except Exception as exc:
            log.warning("expire_stale_forward_signals() failed: %s", exc)
            return 0
